### ISSUE TITLE
proc name too long

### ISSUE THREAD

**Issue by Spuckwaffel** [Y33Tcoder/EventSyncDriver#1]
BYTE target_proc_name[64] = { 0 };
 can only store a process name with the mag length of 32 characters. but what if the process name is longer than that? How can i change that?

**Comment by Y33Tcoder** [comment]
Just make the byte array larger? Say 
BYTE target_proc_name[128] = {0}

P.S. you’d have to make the game_name array in comms.cpp larger also to fit with the increased size too
